export function parseArgs(argv) {
  const args = { _: [] };
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith("--")) {
      args._.push(token);
      continue;
    }
    const key = token.slice(2);
    const next = argv[index + 1];
    if (!next || next.startsWith("--")) {
      args[key] = true;
      continue;
    }
    args[key] = next;
    index += 1;
  }
  return args;
}

export function buildSessionPrompt({ title, task }) {
  if (!title) throw new Error("title is required");
  return [
    `セッション名を「${title}」に固定してください。`,
    "このセッション名をGitHub PR提出名として使います。",
    task ? `タスク: ${task}` : "短く確認だけ返してください。",
  ].join("\n");
}

export function slugifyTitle(title, { prefix = "proposal", date = currentYymmdd() } = {}) {
  if (!title) throw new Error("title is required");
  const slug = title
    .normalize("NFKD")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
  return `${prefix}/${slug || "proposal"}-${date}`;
}

export function buildPrFlow(input) {
  const title = required(input.sessionTitle, "sessionTitle");
  const sessionUrl = required(input.sessionUrl, "sessionUrl");
  const repository = required(input.repository, "repository");
  const baseBranch = input.baseBranch ?? "proposals";
  const headBranch = input.headBranch ?? slugifyTitle(title);
  const body = renderPullRequestBody({
    summary: input.summary ?? "Add or update a proposal artifact.",
    sessionUrl,
    repository,
    baseBranch,
    headBranch,
    changes: input.changes,
  });
  return {
    title,
    repository,
    baseBranch,
    headBranch,
    body,
  };
}

export function renderPullRequestBody(input) {
  const changes = toList(input.changes, ["Add or update the proposal artifact."]);
  return `## Summary

${input.summary}

## Session

- URL: ${input.sessionUrl}

## Scope

- Repository: \`${input.repository}\`
- Base branch: \`${input.baseBranch}\`
- Head branch: \`${input.headBranch}\`

## Changes

${changes.map((item) => `- ${item}`).join("\n")}

## Validation

- [x] Documentation-only change
- [ ] Tests or checks run
- [ ] Not run

Notes:

- Generated by codex-app-browser-chatgpt-ops.

## Follow-up

-
`;
}

export function reviewProposal({ title, body, baseBranch, headBranch, sessionTitle }) {
  const findings = [];
  if (sessionTitle && title !== sessionTitle) {
    findings.push(error("title.sessionTitle", "PR title must match session title."));
  }
  if (baseBranch !== "proposals") {
    findings.push(error("scope.baseBranch", "Base branch must be proposals."));
  }
  if (!headBranch?.startsWith("proposal/")) {
    findings.push(error("scope.headBranch", "Head branch must start with proposal/."));
  }
  for (const section of ["Summary", "Session", "Scope", "Changes", "Validation", "Follow-up"]) {
    if (!new RegExp(`^##\\s+${escapeRegex(section)}\\s*$`, "m").test(body)) {
      findings.push(error("body.section", `Missing section: ${section}`));
    }
  }
  const session = extractSection(body, "Session");
  if (!/^- URL:\s+https?:\/\//m.test(session)) {
    findings.push(error("body.session.url", "Session section must contain URL."));
  }
  const bodyWithoutSession = body.replace(session, "");
  if (/https?:\/\//.test(bodyWithoutSession)) {
    findings.push(error("body.urlLocation", "URLs must appear only in Session section."));
  }
  for (const forbidden of ["project id", "conversation id", "conversation title", "session id", "session title"]) {
    if (new RegExp(`^-\\s*${escapeRegex(forbidden)}\\s*:`, "im").test(body)) {
      findings.push(error("body.provenance", `Forbidden provenance field: ${forbidden}`));
    }
  }
  return {
    ok: findings.length === 0,
    findings,
  };
}

function extractSection(markdown, section) {
  const headingRegex = /^##\s+(.+?)\s*$/gm;
  const matches = [...markdown.matchAll(headingRegex)];
  for (let index = 0; index < matches.length; index += 1) {
    const match = matches[index];
    if (match[1].trim() !== section) continue;
    const next = matches[index + 1];
    const start = match.index + match[0].length;
    const end = next ? next.index : markdown.length;
    return markdown.slice(start, end);
  }
  return "";
}

function error(rule, message) {
  return { level: "error", rule, message };
}

function required(value, name) {
  if (!value) throw new Error(`${name} is required`);
  return value;
}

function toList(value, fallback) {
  if (Array.isArray(value) && value.length > 0) return value;
  if (typeof value === "string" && value.trim()) {
    return value.split("|").map((item) => item.trim()).filter(Boolean);
  }
  return fallback;
}

function currentYymmdd() {
  const now = new Date();
  return `${String(now.getFullYear()).slice(-2)}${String(now.getMonth() + 1).padStart(2, "0")}${String(now.getDate()).padStart(2, "0")}`;
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
