let root='',vad=null,recognizer=null,ready=false,queue=[],vadBuf=new Float32Array(0),history=null
const SR=16000
const join=(a,b)=>{const o=new Float32Array(a.length+b.length);o.set(a);o.set(b,a.length);return o}
function decode(samples){const s=recognizer.createStream();s.acceptWaveform(SR,samples);recognizer.decode(s);const r=recognizer.getResult(s);s.free();return r.text||''}
function boot(m){root=m.root;self.Module={locateFile:p=>new URL('sherpa/'+p,root).href,onRuntimeInitialized:()=>{vad=createVad(self.Module,{sileroVad:{model:'./silero_vad.onnx',threshold:.5,minSilenceDuration:.35,minSpeechDuration:.25,maxSpeechDuration:12,windowSize:512},tenVad:{model:'',threshold:.5,minSilenceDuration:.35,minSpeechDuration:.25,maxSpeechDuration:12,windowSize:256},sampleRate:SR,numThreads:1,provider:'cpu',debug:0,bufferSizeInSeconds:30});recognizer=new OfflineRecognizer({featConfig:{sampleRate:SR,featureDim:80},modelConfig:{transducer:{encoder:'./transducer-encoder.onnx',decoder:'./transducer-decoder.onnx',joiner:'./transducer-joiner.onnx'},tokens:'./tokens.txt',modelType:'transducer',modelingUnit:'cjkchar',numThreads:1,debug:0,provider:'cpu'},decodingMethod:'modified_beam_search',maxActivePaths:4},self.Module);history=new AudioHistory(SR,30);ready=true;postMessage({type:'ready'});for(const q of queue)feed(q);queue=[]}}
  for(const p of ['runtime/audio/history.js','sherpa/sherpa-onnx-asr.js','sherpa/sherpa-onnx-vad.js','sherpa/sherpa-onnx-wasm-main-vad-asr.js'])importScripts(new URL(p,root).href)
}
function feed(chunk){if(!ready){queue.push(chunk);return}history.push(chunk);vadBuf=join(vadBuf,chunk);while(vadBuf.length>=512){vad.acceptWaveform(vadBuf.subarray(0,512));vadBuf=vadBuf.slice(512)}while(!vad.isEmpty()){const seg=vad.front(),samples=Float32Array.from(seg.samples),start=seg.start;vad.pop();const audio=history.withPreroll(start,samples),text=decode(audio),copy=audio.slice();postMessage({type:'final',text,samples:copy},[copy.buffer])}}
self.onmessage=e=>{const m=e.data;if(m.type==='boot')boot(m);else if(m.type==='audio')feed(m.samples);else if(m.type==='flush'&&ready){vad.flush();feed(new Float32Array(0))}}
