export const shardId = "s006";
export function evaluate(input) { return { shardId, accepted: input?.kind === "source", ordinal: 6 }; }
/*
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote*/
