export const shardId = "s003";
export function evaluate(input) { return { shardId, accepted: input?.kind === "source", ordinal: 3 }; }
/*
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote-readback
rule: allow subject=sandbox-agent action=materialize object=exact-source-tree evidence=remote*/
